notifications:
  slack: zewo:VjyVCCQvTOw9yrbzQysZezD1
os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - eval "$(curl -sL https://raw.githubusercontent.com/Zewo/Zewo/5254525d9da56df29346fd76e99529c22034d61d/Scripts/install-swiftenv.sh)"
  - bash ./setup_env.sh
script:
  - swift build --fetch # clones all dependencies
  - rm -rf Packages/*/Tests # deletes dependency's tests until duplicate Package.tests issue can be resolved in SPM. At that point, remove.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        swift build -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib -Xlinker -rpath -Xlinker $(pwd)/.build/debug/;
        swift build --configuration release -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib -Xlinker -rpath -Xlinker $(pwd)/.build/release/;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        swift build -Xcc -I/usr/include -Xlinker -L/usr/lib -Xlinker -rpath -Xlinker $(pwd)/.build/debug/;
        swift build --configuration release -Xcc -I/usr/include -Xlinker -L/usr/lib -Xlinker -rpath -Xlinker $(pwd)/.build/release/;
    fi
  - swift test